module.exports = {
    "die Sekunde": { h: "second", m: "A WOMAN counts every Second.", s: "Se-kun-de" },
    "die Minute": { h: "minute", m: "A WOMAN waits a Minute.", s: "Mi-nu-te" },
    "die Stunde": { h: "ghanta", m: "A WOMAN stands for an Hour.", s: "Stun-de" },
    "der Tag": { h: "din", m: "A MAN plays Tag all day.", s: "Tag" },
    "die Woche": { h: "hafta", m: "A WOMAN works a whole Week.", s: "Wo-che" },
    "das Jahr": { h: "saal", m: "A BABY grows every Year.", s: "Jahr" },
    "der Wochentag": { h: "hafte ka din", m: "A MAN works on a Weekday.", s: "Wo-chen-tag" },
    "der Sonntag": { h: "ravivaar", m: "The Sun (MAN) shines on Sunday.", s: "Sonn-tag" },
    "der Montag": { h: "somvaar", m: "The Moon (MAN) comes on Monday.", s: "Mon-tag" },
    "der Dienstag": { h: "mangalvaar", m: "A MAN serves (Dienst) on Tuesday.", s: "Diens-tag" },
    "der Mittwoch": { h: "budhvaar", m: "A MAN is in the Mid-week.", s: "Mitt-woch" },
    "der Donnerstag": { h: "guruvaar", m: "Thor (MAN) brings Thunder on Thursday.", s: "Don-ners-tag" },
    "der Freitag": { h: "shukravaar", m: "A MAN is Free on Friday.", s: "Frei-tag" },
    "der Samstag": { h: "shanivaar", m: "Sam (MAN) sits on Saturday.", s: "Sams-tag" },
    "das Wochenende": { h: "saptahant", m: "A BABY loves the Weekend.", s: "Wo-chen-en-de" },
    "am Wochenende": { h: "saptahant par", m: "At the weekend.", s: "am Wo-chen-en-de" },
    "der Morgen": { h: "subah", m: "A MAN wakes up in the Morning.", s: "Mor-gen" },
    "der Vormittag": { h: "dopahar se pehle", m: "A MAN works Before Noon.", s: "Vor-mit-tag" },
    "der Mittag": { h: "dopahar", m: "A MAN eats at Noon.", s: "Mit-tag" },
    "der Nachmittag": { h: "dopahar ke baad", m: "A MAN naps After Noon.", s: "Nach-mit-tag" },
    "der Abend": { h: "shaam", m: "A MAN rests in the Evening.", s: "A-bend" },
    "die Nacht": { h: "raat", m: "A WOMAN sleeps at Night.", s: "Nacht" },
    "der Januar": { h: "janvari", m: "Janus (MAN) starts January.", s: "Ja-nu-ar" },
    "der Februar": { h: "farvari", m: "A MAN freezes in February.", s: "Feb-ru-ar" },
    "der März": { h: "march", m: "Mars (MAN) marches in March.", s: "März" },
    "der April": { h: "april", m: "A MAN fools in April.", s: "A-pril" },
    "der Mai": { h: "mai", m: "A MAN enjoys May flowers.", s: "Mai" },
    "der Juni": { h: "june", m: "A MAN jumps in June.", s: "Ju-ni" },
    "der Juli": { h: "july", m: "Julius (MAN) rules July.", s: "Ju-li" },
    "der August": { h: "august", m: "Augustus (MAN) rules August.", s: "Au-gust" },
    "der September": { h: "sitambar", m: "A MAN starts school in September.", s: "Sep-tem-ber" },
    "der Oktober": { h: "aktubar", m: "A MAN drinks beer in October.", s: "Ok-to-ber" },
    "der November": { h: "navambar", m: "A MAN votes in November.", s: "No-vem-ber" },
    "der Dezember": { h: "disambar", m: "A MAN celebrates in December.", s: "De-zem-ber" },
    "der Frühling": { h: "vasant", m: "A MAN springs up in Spring.", s: "Früh-ling" },
    "der Sommer": { h: "garmi", m: "A MAN sweats in Summer.", s: "Som-mer" },
    "der Herbst": { h: "patjhad", m: "A MAN harvests in Autumn.", s: "Herbst" },
    "der Winter": { h: "sardi", m: "A MAN shivers in Winter.", s: "Win-ter" },
    "die Farben": { h: "rang", m: "A WOMAN paints with Colors.", s: "Far-ben" },
    "schwarz": { h: "kaala", m: "Schwarzenegger wears Black.", s: "schwarz" },
    "weiß": { h: "safed", m: "Wise men have White beards.", s: "weiß" },
    "grau": { h: "bhoora/grey", m: "Grow old and Grey.", s: "grau" },
    "blau": { h: "neela", m: "Blow the Blue balloon.", s: "blau" },
    "grün": { h: "hara", m: "Grin when you see Green.", s: "grün" },
    "rot": { h: "laal", m: "Rotten tomatoes are Red.", s: "rot" },
    "gelb": { h: "peela", m: "Yell for Yellow.", s: "gelb" },
    "braun": { h: "bhoora", m: "Brownies are Brown.", s: "braun" },
    "Deutschland": { h: "germany", m: "Land of the Deutsch.", s: "Deutsch-land" },
    "deutsch": { h: "german", m: "Speak Deutsch.", s: "deutsch" },
    "Europa": { h: "europe", m: "Europe is vast.", s: "Eu-ro-pa" },
    "der Europäer": { h: "european", m: "A MAN from Europe.", s: "Eu-ro-pä-er" },
    "europäisch": { h: "european", m: "European style.", s: "eu-ro-pä-isch" },
    "die Himmelsrichtungen": { h: "dishayein", m: "A WOMAN points the Directions.", s: "Him-mels-rich-tun-gen" },
    "der Norden": { h: "uttar", m: "North is up (MAN).", s: "Nor-den" },
    "der Süden": { h: "dakshin", m: "South is down (MAN).", s: "Sü-den" },
    "der Westen": { h: "paschim", m: "West is best (MAN).", s: "Wes-ten" },
    "der Osten": { h: "poorab", m: "East is feast (MAN).", s: "Os-ten" },
    "ab": { h: "se", m: "Ab now, from here.", s: "ab" },
    "aber": { h: "lekin", m: "Aber... but wait!", s: "a-ber" },
    "abfahren": { h: "chalna/ravana hona", m: "Drive off far away.", s: "ab-fah-ren" },
    "die Abfahrt": { h: "ravangi", m: "A WOMAN announces the Departure.", s: "Ab-fahrt" },
    "abgeben": { h: "dena/saunpna", m: "Give away (geben) from (ab).", s: "ab-ge-ben" },
    "abholen": { h: "laana/pick karna", m: "Fetch (holen) from (ab).", s: "ab-ho-len" },
    "der Absender": { h: "bhejne wala", m: "The MAN who sends.", s: "Ab-sen-der" },
    "Achtung": { h: "saavdhaan", m: "Act young, but pay Attention!", s: "Ach-tung" },
    "die Adresse": { h: "pata", m: "A WOMAN writes the Address.", s: "A-dres-se" },
    "allein": { h: "akela", m: "All alone.", s: "al-lein" },
    "also": { h: "toh/isliye", m: "Also means So.", s: "al-so" },
    "alt": { h: "boodha/purana", m: "Old salt.", s: "alt" },
    "das Alter": { h: "umar", m: "A BABY's Age.", s: "Al-ter" },
    "anbieten": { h: "pesh karna", m: "Beat an Offer.", s: "an-bie-ten" },
    "das Angebot": { h: "prastaav", m: "A BABY makes an Offer.", s: "An-ge-bot" },
    "ander": { h: "dusra", m: "Under another.", s: "an-der" },
    "anfangen": { h: "shuru karna", m: "Fang starts the fight.", s: "an-fan-gen" },
    "der Anfang": { h: "shuruat", m: "A MAN starts the Beginning.", s: "An-fang" },
    "anklicken": { h: "click karna", m: "Click on it.", s: "an-kli-cken" },
    "ankommen": { h: "pahunchna", m: "Come on, Arrive!", s: "an-kom-men" },
    "die Ankunft": { h: "aagman", m: "A WOMAN awaits the Arrival.", s: "An-kunft" },
    "ankreuzen": { h: "tick karna", m: "Cross (Kreuz) it.", s: "an-kreu-zen" },
    "anmachen": { h: "chalu karna", m: "Make on (turn on).", s: "an-ma-chen" },
    "sich anmelden": { h: "register karna", m: "Meld into the system.", s: "an-mel-den" },
    "die Anmeldung": { h: "registration", m: "A WOMAN at Registration.", s: "An-mel-dung" },
    "die Anrede": { h: "sambodhan", m: "A WOMAN's Salutation.", s: "An-re-de" },
    "anrufen": { h: "call karna", m: "Roof call.", s: "an-ru-fen" },
    "der Anruf": { h: "call", m: "A MAN makes a Call.", s: "An-ruf" },
    "der Anrufbeantworter": { h: "answering machine", m: "A MAN answers the machine.", s: "An-ruf-be-ant-wor-ter" },
    "die Ansage": { h: "ghoshna", m: "A WOMAN makes an Announcement.", s: "An-sa-ge" },
    "der Anschluss": { h: "connection", m: "A MAN fixes the Connection.", s: "An-schluss" },
    "an sein": { h: "chalu hona", m: "To be on.", s: "an sein" },
    "antworten": { h: "jawab dena", m: "Answer the Ant.", s: "ant-wor-ten" },
    "die Antwort": { h: "jawab", m: "A WOMAN gives an Answer.", s: "Ant-wort" },
    "die Anzeige": { h: "vigyapan", m: "A WOMAN reads the Ad.", s: "An-zei-ge" },
    "anziehen": { h: "pehenna", m: "Pull (ziehen) on clothes.", s: "an-zie-hen" },
    "das Apartment": { h: "flat", m: "A BABY lives in the Apartment.", s: "A-part-ment" },
    "der Apfel": { h: "seb", m: "A MAN eats an Apple.", s: "Ap-fel" },
    "der Appetit": { h: "bhookh", m: "A MAN has a big Appetite.", s: "Ap-pe-tit" },
    "arbeiten": { h: "kaam karna", m: "Arbeit makes you free? No, work.", s: "ar-bei-ten" },
    "die Arbeit": { h: "kaam", m: "A WOMAN goes to Work.", s: "Ar-beit" },
    "arbeitslos": { h: "berozgar", m: "Work-less.", s: "ar-beits-los" },
    "der Arbeitsplatz": { h: "karyasthal", m: "A MAN's Workplace.", s: "Ar-beits-platz" },
    "der Arm": { h: "baazu", m: "A MAN's strong Arm.", s: "Arm" },
    "der Arzt": { h: "doctor", m: "A MAN is a Doctor (Arts).", s: "Arzt" },
    "auch": { h: "bhi", m: "Ouch, me too.", s: "auch" },
    "auf": { h: "par/upar", m: "Up on the roof.", s: "auf" },
    "die Aufgabe": { h: "kaam/task", m: "A WOMAN finishes the Task.", s: "Auf-ga-be" },
    "aufhören": { h: "rokna/band karna", m: "Hear up and stop.", s: "auf-hö-ren" },
    "auf sein": { h: "khula hona", m: "To be open.", s: "auf sein" },
    "aufstehen": { h: "uthna", m: "Stand up!", s: "auf-ste-hen" },
    "der Aufzug": { h: "lift", m: "A MAN takes the Lift up (auf).", s: "Auf-zug" },
    "das Auge": { h: "aankh", m: "A BABY's Eye.", s: "Au-ge" },
    "aus": { h: "bahar/se", m: "Out of the house.", s: "aus" },
    "der Ausflug": { h: "sair/trip", m: "A MAN flies out on a Trip.", s: "Aus-flug" },
    "ausfüllen": { h: "bharna", m: "Fill out fully.", s: "aus-fül-len" },
    "der Ausgang": { h: "exit", m: "A MAN goes out the Exit.", s: "Aus-gang" },
    "die Auskunft": { h: "jaankari", m: "A WOMAN gives Information.", s: "Aus-kunft" },
    "das Ausland": { h: "videsh", m: "A BABY travels Abroad.", s: "Aus-land" },
    "der Ausländer": { h: "videshi", m: "A MAN is a Foreigner.", s: "Aus-län-der" },
    "ausländisch": { h: "videshi", m: "Foreignish.", s: "aus-län-disch" },
    "ausmachen": { h: "band karna", m: "Make out (off).", s: "aus-ma-chen" },
    "die Aussage": { h: "bayan", m: "A WOMAN makes a Statement.", s: "Aus-sa-ge" },
    "aussehen": { h: "dikhna", m: "See out, look like.", s: "aus-se-hen" },
    "aus sein": { h: "khatam hona", m: "To be out/over.", s: "aus sein" },
    "aussteigen": { h: "utarna", m: "Step out.", s: "aus-stei-gen" },
    "der Ausweis": { h: "ID card", m: "A MAN shows his ID.", s: "Aus-weis" },
    "sich ausziehen": { h: "kapde utarna", m: "Pull out (off) clothes.", s: "aus-zie-hen" },
    "das Auto": { h: "gaadi", m: "A BABY plays with a toy Auto.", s: "Au-to" },
    "die Autobahn": { h: "highway", m: "A WOMAN drives on the Autobahn.", s: "Au-to-bahn" },
    "der Automat": { h: "vending machine", m: "A MAN uses the Automat.", s: "Au-to-mat" },
    "automatisch": { h: "automatic", m: "Automatic.", s: "au-to-ma-tisch" },
    "das Baby": { h: "bacha", m: "A BABY is a Baby.", s: "Ba-by" },
    "die Bäckerei": { h: "bakery", m: "A WOMAN runs the Bakery.", s: "Bä-cke-rei" },
    "das Bad": { h: "bathroom", m: "A BABY takes a Bath.", s: "Bad" },
    "baden": { h: "nahana", m: "Bathe in the den.", s: "ba-den" },
    "die Bahn": { h: "train", m: "A WOMAN takes the Bahn (train).", s: "Bahn" },
    "der Bahnhof": { h: "station", m: "A MAN waits at the Station.", s: "Bahn-hof" },
    "der Bahnsteig": { h: "platform", m: "A MAN stands on the Platform.", s: "Bahn-steig" },
    "bald": { h: "jald", m: "Bald men lose hair Soon.", s: "bald" },
    "der Balkon": { h: "balcony", m: "A MAN smokes on the Balcony.", s: "Bal-kon" },
    "die Banane": { h: "kela", m: "A WOMAN eats a Banana.", s: "Ba-na-ne" },
    "die Bank": { h: "bank", m: "A WOMAN goes to the Bank.", s: "Bank" },
    "bar": { h: "cash", m: "Pay cash at the Bar.", s: "bar" },
    "der Bauch": { h: "pet", m: "A MAN has a big Belly (Bauch).", s: "Bauch" },
    "der Baum": { h: "ped", m: "A MAN climbs a Tree (Boom).", s: "Baum" },
    "der Beamte": { h: "adhikari", m: "A MAN is an Official.", s: "Be-am-te" },
    "bedeuten": { h: "matlab hona", m: "What does it denote (bedeuten)?", s: "be-deu-ten" },
    "beginnen": { h: "shuru karna", m: "Begin now.", s: "be-gin-nen" },
    "bei": { h: "paas", m: "By the side.", s: "bei" },
    "beide": { h: "dono", m: "Both bide together.", s: "bei-de" },
    "das Bein": { h: "taang", m: "A BABY hurts its Leg (Bone).", s: "Bein" },
    "das Beispiel": { h: "udaharan", m: "A BABY sets an Example.", s: "Bei-spiel" },
    "zum Beispiel": { h: "udaharan ke liye", m: "For example.", s: "zum Bei-spiel" },
    "bekannt": { h: "mashhoor", m: "Kant is well Known.", s: "be-kannt" },
    "der Bekannte": { h: "jaan-pehchan wala", m: "A MAN I Know.", s: "Be-kann-te" },
    "bekommen": { h: "milna/paana", m: "Become the owner (receive).", s: "be-kom-men" },
    "benutzen": { h: "istemaal karna", m: "Use the nut.", s: "be-nut-zen" },
    "der Beruf": { h: "pesha", m: "A MAN's Profession.", s: "Be-ruf" },
    "besetzt": { h: "vyast/occupied", m: "Seat is beset (occupied).", s: "be-setzt" },
    "besichtigen": { h: "dekhna (visit)", m: "Sightseeing (sicht).", s: "be-sich-ti-gen" },
    "besser": { h: "behtar", m: "Better.", s: "bes-ser" },
    "best": { h: "sabse acha", m: "Best.", s: "best" },
    "bestellen": { h: "order karna", m: "Best tell what to Order.", s: "be-stel-len" },
    "besuchen": { h: "milne aana", m: "Search (suchen) and Visit.", s: "be-su-chen" },
    "das Bett": { h: "bistar", m: "A BABY sleeps in the Bed.", s: "Bett" },
    "bezahlen": { h: "bhugtan karna", m: "Pay the tale (zählen).", s: "be-zah-len" },
    "das Bier": { h: "beer", m: "A BABY shouldn't drink Beer.", s: "Bier" },
    "das Bild": { h: "tasveer", m: "A BABY draws a Picture (Build).", s: "Bild" },
    "billig": { h: "sasta", m: "Bill is Cheap.", s: "bil-lig" },
    "die Birne": { h: "nashpati", m: "A WOMAN eats a Pear.", s: "Bir-ne" },
    "bis": { h: "tak", m: "Until the abyss.", s: "bis" },
    "bisschen": { h: "thoda", m: "A little bit.", s: "biss-chen" },
    "bitte": { h: "kripya", m: "Bitter please.", s: "bit-te" },
    "die Bitte": { h: "anurodh", m: "A WOMAN makes a Request.", s: "Bit-te" },
    "bitten": { h: "maangna", m: "Bid/Ask.", s: "bit-ten" },
    "bitter": { h: "kadwa", m: "Bitter taste.", s: "bit-ter" },
    "bleiben": { h: "rehna/rukna", m: "Stay alive.", s: "blei-ben" },
    "der Bleistift": { h: "pencil", m: "A MAN uses a Pencil.", s: "Blei-stift" },
    "der Blick": { h: "nazar", m: "A MAN takes a Look.", s: "Blick" },
    "die Blume": { h: "phool", m: "A WOMAN smells a Flower (Bloom).", s: "Blu-me" },
    "der Bogen": { h: "dhanush/arch", m: "A MAN shoots with a Bow.", s: "Bo-gen" },
    "böse": { h: "bura/gussa", m: "Bossy and Angry.", s: "bö-se" },
    "brauchen": { h: "zaroorat hona", m: "Bro, I Need it.", s: "brau-chen" },
    "breit": { h: "chauda", m: "Broad and bright.", s: "breit" },
    "der Brief": { h: "khat", m: "A MAN writes a Brief letter.", s: "Brief" },
    "die Briefmarke": { h: "stamp", m: "A WOMAN licks the Stamp.", s: "Brief-mar-ke" },
    "bringen": { h: "laana", m: "Bring it.", s: "brin-gen" },
    "das Brot": { h: "roti/bread", m: "A BABY eats Bread.", s: "Brot" },
    "das Brötchen": { h: "bun/roll", m: "A BABY eats a small Roll.", s: "Bröt-chen" },
    "der Bruder": { h: "bhai", m: "A MAN is a Brother.", s: "Bru-der" },
    "das Buch": { h: "kitaab", m: "A BABY reads a Book.", s: "Buch" },
    "der Buchstabe": { h: "akshar", m: "A MAN writes a Letter (char).", s: "Buch-sta-be" },
    "buchstabieren": { h: "spell karna", m: "Spell the book.", s: "buch-sta-bie-ren" },
    "der Bus": { h: "bus", m: "A MAN drives the Bus.", s: "Bus" },
    "die Butter": { h: "makkhan", m: "A WOMAN spreads Butter.", s: "But-ter" },
    "das Café": { h: "cafe", m: "A BABY sits in the Café.", s: "Ca-fé" },
    "die CD": { h: "CD", m: "A WOMAN plays a CD.", s: "CD" },
    "der Chef": { h: "boss", m: "A MAN is the Chef (Boss).", s: "Chef" },
    "circa": { h: "lagbhag", m: "Circle around, approx.", s: "cir-ca" },
    "der Computer": { h: "computer", m: "A MAN uses the Computer.", s: "Com-pu-ter" },
    "da": { h: "wahan", m: "Da (there) it is.", s: "da" },
    "die Dame": { h: "mahila", m: "A WOMAN is a Dame.", s: "Da-me" },
    "daneben": { h: "bagal mein", m: "Next to it.", s: "da-ne-ben" },
    "danken": { h: "dhanyavad dena", m: "Thank you.", s: "dan-ken" },
    "der Dank": { h: "dhanyavad", m: "A MAN gives Thanks.", s: "Dank" },
    "danke": { h: "shukriya", m: "Thanks.", s: "dan-ke" },
    "dann": { h: "phir", m: "Then done.", s: "dann" },
    "das Datum": { h: "taarikh", m: "A BABY checks the Date.", s: "Da-tum" },
    "dauern": { h: "samay lagna", m: "Endure (dauern) for a long time.", s: "dau-ern" },
    "dein": { h: "tumhara", m: "Thine/Yours.", s: "dein" },
    "denn": { h: "kyunki", m: "Then why?", s: "denn" },
    "der": { h: "woh (masc)", m: "The Man.", s: "der" },
    "dich": { h: "tumhe", m: "Dig you.", s: "dich" },
    "dies": { h: "yeh", m: "This diesel.", s: "dies" },
    "dir": { h: "tumhe (dative)", m: "Dear you.", s: "dir" },
    "die Disco": { h: "disco", m: "A WOMAN dances at the Disco.", s: "Dis-co" },
    "der Doktor": { h: "doctor", m: "A MAN is a Doctor.", s: "Dok-tor" },
    "das Doppelzimmer": { h: "double room", m: "A BABY in a Double Room.", s: "Dop-pel-zim-mer" },
    "das Dorf": { h: "gaon", m: "A BABY lives in the Village (Dorf).", s: "Dorf" },
    "dort": { h: "wahan", m: "Dart over there.", s: "dort" },
    "draußen": { h: "bahar", m: "Drowse outside.", s: "drau-ßen" },
    "drücken": { h: "dabana", m: "Press the truck.", s: "drü-cken" },
    "der Drucker": { h: "printer", m: "A MAN uses the Printer.", s: "Dru-cker" },
    "durch": { h: "ke zariye", m: "Through the door.", s: "durch" },
    "die Durchsage": { h: "ghoshna", m: "A WOMAN hears the Announcement.", s: "Durch-sa-ge" },
    "dürfen": { h: "anumati hona", m: "Do you have permission?", s: "dür-fen" },
    "der Durst": { h: "pyaas", m: "A MAN has Thirst (Dust).", s: "Durst" },
    "sich duschen": { h: "nahana", m: "Douche/Shower.", s: "du-schen" },
    "die Dusche": { h: "shower", m: "A WOMAN takes a Shower.", s: "Du-sche" },
    "die Ecke": { h: "kona", m: "A WOMAN stands in the Corner.", s: "E-cke" },
    "die Ehefrau": { h: "patni", m: "A WOMAN is a Wife.", s: "E-he-frau" },
    "der Ehemann": { h: "pati", m: "A MAN is a Husband.", s: "E-he-mann" },
    "das Ei": { h: "anda", m: "A BABY eats an Egg (Eye).", s: "Ei" },
    "eilig": { h: "jaldi mein", m: "Oily fast.", s: "ei-lig" },
    "ein": { h: "ek", m: "One.", s: "ein" },
    "einfach": "simple",
    "der Eingang": "the entrance",
    "einkaufen": "to shop",
    "einladen": "to invite",
    "die Einladung": "the invitation",
    "einmal": "once",
    "einsteigen": "to get on",
    "der Eintritt": "the admission",
    "das Einzelzimmer": "the single room",
    "die Eltern": "the parents",
    "die E-mail": "the email",
    "der Empfänger": "the recipient",
    "empfehlen": "to recommend",
    "enden": "to end",
    "das Ende": "the end",
    "entschuldigen": "to apologize",
    "die Entschuldigung": "the apology",
    "er": "he",
    "das Ergebnis": "the result",
    "erklären": "to explain",
    "erlauben": "to allow",
    "der Erwachsene": "the adult",
    "erzählen": "to tell",
    "es": "it",
    "essen": "to eat",
    "das Essen": "the food",
    "euer": "your",
    "fahren": "to drive",
    "der Fahrer": "the driver",
    "die Fahrkarte": "the ticket",
    "das Fahrrad": "the bicycle",
    "falsch": "wrong",
    "die Familie": "the family",
    "der Familienname": "the surname",
    "der Familienstand": "the marital status",
    "die Farbe": "the color",
    "das Fax": "the fax",
    "die Feier": "the celebration",
    "feiern": "to celebrate",
    "fehlen": "to be missing",
    "der Fehler": "the mistake",
    "fernsehen": "to watch TV",
    "fertig": "finished",
    "das Feuer": "the fire",
    "das Fieber": "the fever",
    "der Film": "the film",
    "finden": "to find",
    "die Firma": "the company",
    "der Fisch": "the fish",
    "die Flasche": "the bottle",
    "das Fleisch": "the meat",
    "fliegen": "to fly",
    "abfliegen": "to take off",
    "der Abflug": "the departure",
    "der Flughafen": "the airport",
    "das Flugzeug": "the airplane",
    "das Formular": "the form",
    "das Foto": "the photo",
    "fragen": "to ask",
    "die Frage": "the question",
    "die Frau": "the woman",
    "fremd": "foreign",
    "frei": "free",
    "die Freizeit": "the free time",
    "sich freuen": "to be happy",
    "der Freund": "the friend",
    "früher": "earlier",
    "frühstücken": "to eat breakfast",
    "das Frühstück": "the breakfast",
    "die Führung": "the guided tour",
    "für": "for",
    "der Fuß": "the foot",
    "der Fußball": "the football",
    "der Garten": "the garden",
    "der Gast": "the guest",
    "geben": "to give",
    "geboren": "born",
    "das Geburtsjahr": "the year of birth",
    "der Geburtsort": "the place of birth",
    "der Geburtstag": "the birthday",
    "gefallen": "to please",
    "gegen": "against",
    "gehen": "to go",
    "gehören": "to belong",
    "das Geld": "the money",
    "das Gemüse": "the vegetables",
    "das Gepäck": "the luggage",
    "gerade": "straight",
    "geradeaus": "straight ahead",
    "gern": "gladly",
    "das Geschäft": "the shop",
    "das Geschenk": "the gift",
    "die Geschwister": "the siblings",
    "das Gespräch": "the conversation",
    "gestern": "yesterday",
    "gestorben": "died",
    "das Getränk": "the drink",
    "das Gewicht": "the weight",
    "gewinnen": "to win",
    "das Glas": "the glass",
    "glauben": "to believe",
    "gleich": "equal",
    "das Gleis": "the track",
    "das Glück": "the luck",
    "glücklich": "happy",
    "der Glückwunsch": "the congratulation",
    "Grad": "degree",
    "gratulieren": "to congratulate",
    "grillen": "to grill",
    "groß": "big",
    "die Größe": "the size",
    "die Großeltern": "the grandparents",
    "die Großmutter": "the grandmother",
    "der Großvater": "the grandfather",
    "die Gruppe": "the group",
    "der Gruß": "the greeting",
    "gültig": "valid",
    "günstig": "cheap",
    "gut": "good",
    "das Haar": "the hair",
    "haben": "to have",
    "das Hähnchen": "the chicken",
    "die Halbpension": "the half board",
    "die Halle": "the hall",
    "hallo": "hello",
    "halten": "to stop",
    "die Haltestelle": "the stop",
    "die Hand": "the hand",
    "das Handy": "the mobile phone",
    "das Haus": "the house",
    "die Hausaufgabe": "the homework",
    "die Hausfrau": "the housewife",
    "der Hausmann": "the househusband",
    "die Heimat": "the home",
    "heiraten": "to marry",
    "heißen": "to be called",
    "helfen": "to help",
    "hell": "bright",
    "der Herd": "the stove",
    "der Herr": "the gentleman",
    "herzlich": "cordial",
    "heute": "today",
    "hier": "here",
    "die Hilfe": "the help",
    "hinten": "behind",
    "das Hobby": "the hobby",
    "hoch": "high",
    "die Hochzeit": "the wedding",
    "holen": "to fetch",
    "hören": "to hear",
    "das Hotel": "the hotel",
    "der Hund": "the dog",
    "der Hunger": "the hunger",
    "ich": "I",
    "ihr/ihm/ihn": "her/him/him",
    "immer": "always",
    "in": "in",
    "die Information": "the information",
    "international": "international",
    "das Internet": "the internet",
    "ja": "yes",
    "die Jacke": "the jacket",
    "jed-": "every",
    "jetzt": "now",
    "der Job": "the job",
    "der Jugendliche": "the teenager",
    "jung": "young",
    "der Junge": "the boy",
    "der Kaffee": "the coffee",
    "kaputt": "broken",
    "die Karte": "the card",
    "die Kartoffel": "the potato",
    "die Kasse": "the cash register",
    "kaufen": "to buy",
    "kein": "no",
    "kennen": "to know",
    "kennenlernen": "to get to know",
    "das Kind": "the child",
    "der Kindergarten": "the kindergarten",
    "das Kino": "the cinema",
    "der Kiosk": "the kiosk",
    "klar": "clear",
    "die Klasse": "the class",
    "die Kleidung": "the clothing",
    "klein": "small",
    "kochen": "to cook",
    "der Koffer": "the suitcase",
    "der Kollege": "the colleague",
    "kommen": "to come",
    "können": "can",
    "das Konto": "the account",
    "der Kopf": "the head",
    "kosten": "to cost",
    "kriegen": "to get",
    "die Küche": "the kitchen",
    "der Kuchen": "the cake",
    "der Kugelschreiber": "the ballpoint pen",
    "der Kühlschrank": "the refrigerator",
    "kulturell": "cultural",
    "sich kümmern": "to take care",
    "der Kunde": "the customer",
    "der Kurs": "the course",
    "kurz": "short",
    "lachen": "to laugh",
    "der Laden": "the shop",
    "das Land": "the country",
    "lang": "long",
    "lange": "long",
    "langsam": "slow",
    "laufen": "to run",
    "laut": "loud",
    "leben": "to live",
    "das Leben": "the life",
    "die Lebensmittel": "the groceries",
    "ledig": "single",
    "legen": "to lay",
    "der Lehrer": "the teacher",
    "leicht": "easy",
    "leider": "unfortunately",
    "leise": "quiet",
    "lernen": "to learn",
    "lesen": "to read",
    "letzt": "last",
    "die Leute": "the people",
    "das Licht": "the light",
    "lieb": "dear",
    "lieben": "to love",
    "lieber": "rather",
    "Lieblings-": "favorite",
    "das Lied": "the song",
    "liegen": "to lie",
    "links": "left",
    "der Lkw": "the truck",
    "das Lokal": "the pub",
    "die Lösung": "the solution",
    "lustig": "funny",
    "machen": "to do",
    "das Mädchen": "the girl",
    "man": "one",
    "der Mann": "the man",
    "männlich": "male",
    "die Maschine": "the machine",
    "das Meer": "the sea",
    "mehr": "more",
    "mein": "my",
    "meist": "mostly",
    "der Mensch": "the human",
    "mieten": "to rent",
    "die Miete": "the rent",
    "die Milch": "the milk",
    "mit": "with",
    "mitbringen": "to bring along",
    "mitkommen": "to come along",
    "mitmachen": "to participate",
    "mitnehmen": "to take along",
    "die Mitte": "the middle",
    "die Möbel": "the furniture",
    "möchten": "would like",
    "mögen": "to like",
    "möglich": "possible",
    "der Moment": "the moment",
    "morgen": "tomorrow",
    "müde": "tired",
    "der Mund": "the mouth",
    "müssen": "must",
    "die Mutter": "the mother",
    "nach": "after",
    "nächst": "next",
    "der Name": "the name",
    "nehmen": "to take",
    "nein": "no",
    "neu": "new",
    "nicht": "not",
    "nichts": "nothing",
    "nie": "never",
    "noch": "still",
    "normal": "normal",
    "die Nummer": "the number",
    "nur": "only",
    "oben": "above",
    "das Obst": "the fruit",
    "oder": "or",
    "öffnen": "to open",
    "oft": "often",
    "ohne": "without",
    "das Öl": "the oil",
    "die Oma": "the grandma",
    "der Opa": "the grandpa",
    "die Ordnung": "the order",
    "der Ort": "the place",
    "das Papier": "the paper",
    "die Papiere": "the papers",
    "der Partner": "the partner",
    "die Partnerin": "the partner",
    "die Party": "the party",
    "der Pass": "the passport",
    "die Pause": "the break",
    "der Plan": "the plan",
    "der Platz": "the place",
    "die Polizei": "the police",
    "die Pommes frites": "the french fries",
    "die Post": "the post office",
    "die Postleitzahl": "the zip code",
    "das Praktikum": "the internship",
    "die Praxis": "the practice",
    "der Preis": "the price",
    "das Problem": "the problem",
    "der Prospekt": "the brochure",
    "die Prüfung": "the exam",
    "pünktlich": "punctual",
    "Rad fahren": "to cycle",
    "rauchen": "to smoke",
    "der Raum": "the room",
    "die Rechnung": "the bill",
    "rechts": "right",
    "regnen": "to rain",
    "der Regen": "the rain",
    "der Reis": "the rice",
    "reisen": "to travel",
    "die Reise": "the trip",
    "das Reisebüro": "the travel agency",
    "der Reiseführer": "the travel guide",
    "reparieren": "to repair",
    "die Reparatur": "the repair",
    "das Restaurant": "the restaurant",
    "die Rezeption": "the reception",
    "richtig": "correct",
    "riechen": "to smell",
    "ruhig": "quiet",
    "der Saft": "the juice",
    "sagen": "to say",
    "der Salat": "the salad",
    "das Salz": "the salt",
    "der Satz": "the sentence",
    "die S-Bahn": "the suburban train",
    "der Schalter": "the counter",
    "scheinen": "to shine",
    "schicken": "to send",
    "das Schild": "the sign",
    "der Schinken": "the ham",
    "schlafen": "to sleep",
    "schlecht": "bad",
    "schließen": "to close",
    "geschlossen": "closed",
    "der Schluss": "the end",
    "der Schlüssel": "the key",
    "schmecken": "to taste",
    "schnell": "fast",
    "schon": "already",
    "schön": "beautiful",
    "der Schrank": "the cupboard",
    "schreiben": "to write",
    "der Schuh": "the shoe",
    "die Schule": "the school",
    "der Schüler": "the student",
    "schwer": "heavy",
    "die Schwester": "the sister",
    "schwimmen": "to swim",
    "das Schwimmbad": "the swimming pool",
    "der See": "the lake",
    "sehen": "to see",
    "die Sehenswürdigkeit": "the sight",
    "sehr": "very",
    "sein": "to be",
    "an sein": "to be on",
    "auf sein": "to be open",
    "weg sein": "to be away",
    "zu sein": "to be closed",
    "seit": "since",
    "selbstständig": "independent",
    "sich": "oneself",
    "sie": "she",
    "Sie": "you",
    "sitzen": "to sit",
    "so": "so",
    "das Sofa": "the sofa",
    "sofort": "immediately",
    "der Sohn": "the son",
    "sollen": "should",
    "die Sonne": "the sun",
    "spät": "late",
    "später": "later",
    "die Speisekarte": "the menu",
    "spielen": "to play",
    "der Sport": "the sport",
    "die Sprache": "the language",
    "sprechen": "to speak",
    "die Stadt": "the city",
    "stehen": "to stand",
    "die Stelle": "the position",
    "stellen": "to place",
    "der Stock": "the floor",
    "die Straße": "the street",
    "die Straßenbahn": "the tram",
    "studieren": "to study",
    "das Studium": "the study",
    "der Student": "the student",
    "die Stunde": "the hour",
    "suchen": "to search",
    "tanzen": "to dance",
    "die Tasche": "the bag",
    "das Taxi": "the taxi",
    "der Tee": "the tea",
    "der Teil": "the part",
    "telefonieren": "to phone",
    "das Telefon": "the telephone",
    "das Termin": "the appointment",
    "der Test": "the test",
    "teuer": "expensive",
    "das Text": "the text",
    "das Thema": "the topic",
    "das Ticket": "the ticket",
    "der Tisch": "the table",
    "die Tochter": "the daughter",
    "die Toilette": "the toilet",
    "die Tomate": "the tomato",
    "tot": "dead",
    "treffen": "to meet",
    "die Treppe": "the stairs",
    "trinken": "to drink",
    "tschüss": "bye",
    "tun": "to do",
    "über": "over",
    "übernachten": "to stay overnight",
    "überweisen": "to transfer",
    "die Uhr": "the clock",
    "um": "around",
    "umziehen": "to move",
    "und": "and",
    "unser": "our",
    "unten": "below",
    "unter": "under",
    "der Unterricht": "the lesson",
    "unterschreiben": "to sign",
    "die Unterschrift": "the signature",
    "der Urlaub": "the vacation",
    "der Vater": "the father",
    "verboten": "forbidden",
    "verdienen": "to earn",
    "der Verein": "the club",
    "verheiratet": "married",
    "verkaufen": "to sell",
    "der Verkäufer": "the seller",
    "vermieten": "to rent out",
    "der Vermieter": "the landlord",
    "verstehen": "to understand",
    "die Verwandte": "the relative",
    "viel": "much",
    "vielleicht": "maybe",
    "von": "from",
    "vor": "before",
    "der Vorname": "the first name",
    "die Vorsicht": "the caution",
    "(sich) vorstellen": "to introduce",
    "die Vorwahl": "the area code",
    "wandern": "to hike",
    "wann": "when",
    "warten": "to wait",
    "warum": "why",
    "was": "what",
    "was für ein": "what kind of",
    "waschen": "to wash",
    "das Wasser": "the water",
    "weh tun": "to hurt",
    "weiblich": "female",
    "der Wein": "the wine",
    "weit": "far",
    "weiter": "further",
    "welch": "which",
    "die Welt": "the world",
    "wenig": "little",
    "wer": "who",
    "werden": "to become",
    "das Wetter": "the weather",
    "wichtig": "important",
    "wie": "how",
    "wiederholen": "to repeat",
    "das Wiederhören": "the hearing again",
    "das Wiedersehen": "the reunion",
    "wie viel": "how much",
    "willkommen": "welcome",
    "der Wind": "the wind",
    "wir": "we",
    "wissen": "to know",
    "wo": "where",
    "woher": "where from",
    "wohin": "where to",
    "wohnen": "to live",
    "die Wohnung": "the apartment",
    "wollen": "to want",
    "das Wort": "the word",
    "wunderbar": "wonderful",
    "zahlen": "to pay",
    "die Zeit": "the time",
    "zurzeit": "currently",
    "die Zeitung": "the newspaper",
    "die Zigarette": "the cigarette",
    "das Zimmer": "the room",
    "der Zoll": "the customs",
    "zu": "to",
    "zufrieden": "satisfied",
    "der Zug": "the train",
    "zurück": "back",
    "zusammen": "together",
    "zwischen": "between"
};
